// TODO: Discovery how to store this credentials in a secure way

export const config = {
  url: 'https://api.pinata.cloud',
  gatewayUrl: 'https://gateway.pinata.cloud',
  token:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIzNGJhOTQ4OC1lZDVkLTQzZTctOGQzMi1mNzkwODAyZmFhMTIiLCJlbWFpbCI6ImpvbmF0aGFuLmJlcnRvbGRpQGFlLnN0dWRpbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImlkIjoiRlJBMSIsImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxfSx7ImlkIjoiTllDMSIsImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxfV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJmZjI1MzEzYzBlZGE2YzgwNTk5NSIsInNjb3BlZEtleVNlY3JldCI6IjA0NTJjMmQ1NjE1NzI2ZDEwMmQyNDc4MDVlY2EyNzZmMDY2NGE4YjI3OTQ4ZGMzNDI0MzVhYzg2ZjQ3NmI1M2YiLCJpYXQiOjE2ODc4OTQ2OTZ9.raXLmhNtmbuv0dWFcmJFLf_hNTv8W0sfmSiHWqQ7pcg',
};
